---
kind: pipeline
name: main

platform:
  os: linux
  arch: amd64

steps:
- name: npm
  pull: default
  image: node:10.15.0
  commands:
    - bash ./drone/npm.sh
  environment:
    NPM_TOKEN:
      from_secret: npm_token

- name: publish
  pull: default
  image: node:10.15.0
  commands:
    - bash ./drone/publish.sh

trigger:
  event:
    - pull_request
    - tag
